FileVersion = 1
Dependencies = {corlib = "*", lz4-beef = "*"}

[Project]
Name = "example"
TargetType = "BeefGUIApplication"
StartupObject = "example.Program"

[Configs.Debug.Win64]
DebugCommandArguments = "test.txt"
