FileVersion = 1

[Project]
Name = "lz4-beef"
DefaultNamespace = "lz4"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\lz4_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\lz4.lib"]
